### ISSUE TITLE
自定义前缀使用不正常

### ISSUE THREAD

**Issue by HoneyLuka** [NathanLi/iOSCategoryPropertyDynamicSupport#2]
你好，我将代码引入项目后，使用nl前缀没有问题，但是使用自己的前缀（目前我使用的前缀是"app_"），似乎无法正常使用，访问属性会提示unrecognized selector sent to instance

**Comment by NathanLi** [comment]
是这么使用的吗：
```
/**
 *  @brief 设置动态属性的前辍名
 *         注意，只有在 main.m 文件中先调用本方法才有效；只有能设置一次，多次赋值会被忽略
 *         可以为 NULL 和 ""，但不建议这么设置
 *

int main(int argc, char * argv[]) {
  @autoreleasepool {
    nl_dynamicPropertySetPrefix("af_");
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
 }
}
```

**Comment by HoneyLuka** [comment]
没错，但是似乎没有生效，在我设置成app_后，app_无效，但nl_的前缀依然可以使用。跟我的项目本身是OC+Swift混编的原因有关吗？

昨天走的匆忙没有详细测试，今天我可以测试后再来跟你确定下

**Comment by HoneyLuka** [comment]
我在项目中给UIView增加了几个属性，断点调试的结果为:
```
const char *nl_dynamicPropertyPrefix() {
  return kNLDynamicPropertyPrefix;
}
```
这个方法会先于main.m中的main方法调用。
调用栈如图
![8f5aa871-5025-4cb8-a39b-5c7b5e91f633](https://cloud.githubusercontent.com/assets/4635725/20613907/9bd74300-b303-11e6-8375-7489f791073f.png)

之后才会调用main方法执行nl_dynamicPropertySetPrefix()来修改前缀。
这个调用顺序应该就是无法正常使用的原因了。

之后我又尝试了在代码中硬改默认前缀，是可用的。
```
#define kNLDynamicPropertyPrefixDefaultValue "app_"
```

**Comment by HoneyLuka** [comment]
目前还遇到一个问题是，如果将一个值设置成nil会调用下面这个方法
```
void __NL__object_dynamicSetterIMP(id self, SEL _cmd, id arg) {
  NSString *propertyName = [[self class] nl_dynamicPropertyNameWithSelctor:_cmd];
  [self willChangeValueForKey:propertyName];
  [[self nl_dynamicPropertyDictionary] setObject:arg forKey:propertyName];
  [self didChangeValueForKey:propertyName];
}
```
由于没有对arg这个参数做nil判断，直接写入dict会导致抛出异常

**Comment by NathanLi** [comment]
欢迎 push request.

**Comment by NathanLi** [comment]
@HoneyLuka  你提的问题，都已经修复了

**Comment by HoneyLuka** [comment]
非常感谢
